FROM python:3.11-slim

WORKDIR /app

# Copiar requirements
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar código necesario para el monitor
COPY common/ ./common/
COPY monitor/ ./monitor/

WORKDIR /app

CMD ["python", "-m", "monitor.monitor"]

