FROM python:3.11-slim

WORKDIR /app

# Copiar requirements
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar código del cliente
COPY client/ ./client/

WORKDIR /app/client

CMD ["python", "main.py"]
