FROM python:3.11-slim

WORKDIR /app

# Copiar requirements
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar código
COPY middleware/ ./middleware/
COPY workers/ ./workers/

WORKDIR /app

# El comando se especificará en el docker-compose
CMD ["python", "-m", "workers.filter.filter_year"]
